# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Eliott Veyrier
title: Concepteur Développeur d'applications
email: eliottarloveyrier@live.fr
website: hasenn.github.io

# Social links
twitter_username: Allworknopl4y1
github_username:  hasenn
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: hazen_o
# linkedin_username: 
# pinterest_username: jekyll
# youtube_username: g
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
Diplomé de la faculté des sciences de montpellier, je cherche a me reconvertir dans le développement informatique, qui m'a toujours interessé.
Je suis rigoureux, curieux, et je sait m'integrer dans une équipe. (incomplet)


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
