# Site
repository: hasenn/hasenn.github.io
favicon: images/favicon.ico

# Personal info
name: Eliott Veyrier
title: Concepteur Développeur d'applications
email: eliottarloveyrier@live.fr
website: hasenn.github.io

# Social links
twitter_username: Allworknopl4y1
github_username:  hasenn
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: hazen_o
# linkedin_username: 
# pinterest_username: jekyll
# youtube_username: g
# googleplus_username: +jekyll

# About Section
about_title: A propos de moi
#about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  

  Diplomé de la faculté des sciences de montpellier, je cherche a me reconvertir dans le développement informatique, qui m'a toujours interessé.

  Âgé de 21 ans, je suis curieux, rigoureux, et je sait faire preuve de savoir-être pour m'intègrer dans une équipe.

  Mes Compétences :

  ![Codewars Badge](https://www.codewars.com/users/Hasenn/badges/small)

  -  Méthodologies : <mark>UML</mark> <mark>Agile</mark>
  -  Programmation / Scripting : <mark>Python</mark> <mark>C#</mark> <mark>C/C++</mark> <mark>F#</mark> <mark>Caml</mark> 
  <mark>JavaScript</mark> <mark>WebGL</mark> <mark>GLSL</mark> <mark>PowerShell</mark> <mark>Shell Unix</mark>
  -  Markdown / Web : <mark>Xml</mark> <mark>Html5</mark> <mark>Css3</mark> <mark>Json</mark> <mark>Yaml</mark> <mark>Toml</mark>
  -  Bases de données : <mark>MariaDB</mark> <mark>PostgreSQL</mark>
  -  Outils et technologies : <mark>Git</mark> <mark>Unity</mark> <mark>Godot 3</mark> <mark>Discord API</mark>
  


# Projects Section
projects_title: Projets

# Experience Section
experience_title: Expérience

# Education Section
educaton_title: Education

# More Section
more_title: Loisirs
more_content: | # this will include new lines to allow paragraphs
  * Musique : Improvisation jazz au piano et à la guitare, M.A.O. avec un home-studio, composition dans le style des bandes originales de mes jeux préférés.

  * Sports et jeux compétitifs d’équipe : Basket-Ball, Counter-Strike, Age of Empires 2, ...


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
